### ISSUE TITLE
Issues here

### ISSUE THREAD

**Issue by asiaon123** [asiaon123/ReviewBoardPlugin4IntelliJ#1]
Leave a issue here!

**Comment by asiaon123** [comment]
T

**Comment by xujiaxungo** [comment]
When I try to submit,it's remind me this error. Uploading diff virtual file error, Get inputstram from connection error, Server returned HTTP response code: 400 for URL: http://review.xxx.com/api/review-requests/1631/diffs/.what should I do ?

**Comment by asiaon123** [comment]
你的review board的服务的api版本是多少?

**Comment by xujiaxungo** [comment]
review board 的版本号是2.5.7

**Comment by asiaon123** [comment]
方便把你的配置信息截图在这里我看一下吗

**Comment by xujiaxungo** [comment]
[是插件里头的配置信息么？这玩意儿我也刚用。。刚转码农有些术语还整不明白。。哥们有啥QQ或者啥的联系方式不
![otjact nm2 025oc_ s vg](https://user-images.githubusercontent.com/34361481/33752442-be6bd3e8-dc1c-11e7-8942-8b157a7633ec.png)

**Comment by asiaon123** [comment]
对的,你试了点击Test Login了吗?账号是提示登录成功吗?

**Comment by xujiaxungo** [comment]
是成功的

**Comment by xujiaxungo** [comment]
我试着用命令行上传现在提示
ERROR: Error validating diff

/lxx/trunk/src/main/webapp/console/xxx.jsp: The file was not found in the repository. (HTTP 400, API Error 207)
是不是电脑上其他有需要关联东西没有配置好才造成的这一系列错误？

**Comment by asiaon123** [comment]
命令行也出问题?
远程的reviewboard有你提交代码的这个仓库吗?

**Comment by asiaon123** [comment]
方便粘贴一下你使用命令行生成的diff file吗?

**Comment by xujiaxungo** [comment]
- -其实整一套流程都不甚清楚。。我自己也找不到.diff文件在哪。。只是在命令行输入rbt post就出来这么个提示。可能根本没生成成功

**Comment by xujiaxungo** [comment]
![99hyc 8 zg6xjkwp5vn 67](https://user-images.githubusercontent.com/34361481/33795175-753776ae-dd17-11e7-9945-ea53a5e8113a.png)我搜索了下放代码的文档下有这么些.diff文件。。哪个是有用的？

**Comment by xujiaxungo** [comment]
感觉像是地址不对。我在.reviewboardrc文件里比方配置的‘REPOSITORY_URL=‘http://code.lxx.com/svn/lxx’。这个就是代码存放的实际地址，在地址栏输入就能访问。。是有什么格式上的问题吗？除了这个.reviewboardrc文件我还要在其他地方配置这个地址么？

**Comment by asiaon123** [comment]
应该是你reviewboard的服务配置的有问题,看你发的仓库地址,没有分支信息,所以生成diff文件会错误,找你们的reviewboard维护者重新配置一下吧

**Comment by xujiaxungo** [comment]
因为单位大多人都还用的eclipse，是配合tao-reviewboard这个插件在用的。。除了我大家都能上传。。是IDEA设置上跟eclipse大相径庭么？

**Comment by xujiaxungo** [comment]
现在的组织方式是 项目名称/工程名称/trunk  不是trunk/项目名称/工程名称。。你说的分支是lxx的子文件夹，这样也有影响的么？

**Comment by asiaon123** [comment]
哥们,加我QQ415665891,详细聊下
