### ISSUE TITLE
Cannot find all repositories when total number is more than 25

### ISSUE THREAD

**Issue by linglingT** [asiaon123/ReviewBoardPlugin4IntelliJ#4]
i try to get all repositories but failed when total number is more than 25 repositories. And after debug i found there is max-results parameter in request when getting response, could you grant commit code access to me or will you kindly fix it? 
ex:
api/repositories/?max-results=200

**Comment by asiaon123** [comment]
Sorry for replying late, a new version(v3.0.4) has been pushed to solve this problem temporarily, you could get update notification soon.
